# cliff.toml (put in repo root)
[changelog]
header = "## Changelog"
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}## [unreleased]{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | trim }}
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = false          # <- important for your current messages
filter_unconventional = false
topo_order = true
sort_commits = "oldest"

# Single bucket that matches anything, so every commit is listed
[[git.commit_parsers]]
message = ".*"
group = "Changes"
